### ISSUE TITLE
"unknown conversion" with descheduler policy post-1.14

### ISSUE THREAD

**Issue by damemi** [openshift/cluster-kube-descheduler-operator#116]
Using a descheduler image built after the go1.14 bump upstream results in the following error when used with our operator:
```
$ oc logs pod/cluster-64fd56cddf-c4mf7
E0717 15:33:52.633020       1 server.go:46] failed converting versioned policy to internal policy version: converting (v1alpha1.DeschedulerPolicy) to (api.DeschedulerPolicy): unknown conversion
```

I haven't verified yet if this is only an error with our operator and how we generate the policy, or if it's an issue with the descheduler's api itself. The error arises from here: https://github.com/kubernetes-sigs/descheduler/blob/267b0837dc3085c387d1ee6bf76050bf0db91c9a/pkg/descheduler/policyconfig.go#L51

/kind bug
/priority critical-urgent

**Comment by damemi** [comment]
Ok I'm seeing this without our operator when I build from my upstream 1.19 rebase branch (https://github.com/kubernetes-sigs/descheduler/pull/337), but not when I build it from master. So I don't think it's related to go 1.14, but rather the 1.19 rebase

**Comment by damemi** [comment]
Closing this, false alarm and something I'll just have to react to for the 1.19 bump

**Comment by szymonhwheels-cloud** [comment]
> Using a descheduler image built after the go1.14 bump upstream results in the following error when used with our operator:
> 
> ```
> $ oc logs pod/cluster-64fd56cddf-c4mf7
> E0717 15:33:52.633020       1 server.go:46] failed converting versioned policy to internal policy version: converting (v1alpha1.DeschedulerPolicy) to (api.DeschedulerPolicy): unknown conversion
> ```
> 
> I haven't verified yet if this is only an error with our operator and how we generate the policy, or if it's an issue with the descheduler's api itself. The error arises from here: https://github.com/kubernetes-sigs/descheduler/blob/267b0837dc3085c387d1ee6bf76050bf0db91c9a/pkg/descheduler/policyconfig.go#L51
> 
> /kind bug /priority critical-urgent
