### ISSUE TITLE
LowNodeUtilization "NumberOfNodes" not working

### ISSUE THREAD

**Issue by titou10titou10** [openshift/cluster-kube-descheduler-operator#123]
In the example and in the documentation, for the `LowNodeUtilization` stragegy the parameters`"NumberOfNodes"`is used in many places
It does not work.  It is due to those lines of code that "switchi" on the "toLower" value of the parameter, but test on non lowercase value
Using`"nodes"` as parameter name works 

This is due to those lines: 
https://github.com/openshift/cluster-kube-descheduler-operator/blob/73b98f8b16ccbf80d5248481aba78e6a52c4a580/pkg/operator/target_config_reconciler.go#L181-L196

**Comment by damemi** [comment]
/close
this parameter is no longer available with the GA release of the operator and the introduction of descheduler profiles

**Comment by szymonhwheels-cloud** [comment]
> In the example and in the documentation, for the `LowNodeUtilization` stragegy the parameters`"NumberOfNodes"`is used in many places It does not work. It is due to those lines of code that "switchi" on the "toLower" value of the parameter, but test on non lowercase value Using`"nodes"` as parameter name works
> 
> This is due to those lines:
> 
> https://github.com/openshift/cluster-kube-descheduler-operator/blob/73b98f8b16ccbf80d5248481aba78e6a52c4a580/pkg/operator/target_config_reconciler.go#L181-L196
