### ISSUE TITLE
LowNodeUtilization: "TargetThreshold" params not translated correctly, overriden by "Threshold" values

### ISSUE THREAD

**Issue by titou10titou10** [openshift/cluster-kube-descheduler-operator#124]
The "TargetThreshold" values are not correctly translated in the cluster Configmap. The "TargetThreshold" values are taken from the "Threshold" values
As is, the Descheduler operator is not usable, except if we update the generated cluster ConfighMap by hand and we don't touch the`Descheduler`instance..

This "strategy":

    strategies:
      - name: "LowNodeUtilization"
        params:
          - name: "CPUThreshold"
            value: "10"
          - name: "MemoryThreshold"
            value: "20"
          - name: "PodsThreshold"
            value: "30"
          - name: "CPUTargetThreshold"
            value: "40"
          - name: "MemoryTargetThreshold"
            value: "50"
          - name: "PodsTargetThreshold"
            value: "60"

Is translated in "cluster" ConfigMap to:

     strategies:
      LowNodeUtilization:
        enabled: true
        params:
          nodeResourceUtilizationThresholds:
            targetThresholds:
              cpu: 10
              memory: 20
              pods: 30
            thresholds:
              cpu: 10
              memory: 20
              pods: 30

**Comment by damemi** [comment]
/close
this was fixed in https://github.com/openshift/cluster-kube-descheduler-operator/pull/121
