### ISSUE TITLE
Please prepare bundle for OCP 4.7

### ISSUE THREAD

**Issue by Ximinhan** [openshift/cluster-kube-descheduler-operator#146]
Now that we are fully branched for 4.7, please prepare your operator to supply a 4.7 bundle, so that 4.7 operator publishing works and doesn't overwrite 4.6 bundles. This means at least updating the package.yaml under
https://github.com/openshift/cluster-kube-descheduler-operator/tree/master/manifests

@jcantrill @richm

Reference: openshift/ocp-build-data#708

**Comment by damemi** [comment]
/assign @ingvagabund 
have we already done this?

**Comment by ingvagabund** [comment]
https://github.com/openshift/cluster-kube-descheduler-operator/pull/145
/close

**Comment by szymonhwheels-cloud** [comment]
> Now that we are fully branched for 4.7, please prepare your operator to supply a 4.7 bundle, so that 4.7 operator publishing works and doesn't overwrite 4.6 bundles. This means at least updating the package.yaml under https://github.com/openshift/cluster-kube-descheduler-operator/tree/master/manifests
> 
> [@jcantrill](https://github.com/jcantrill) [@richm](https://github.com/richm)
> 
> Reference: [openshift-eng/ocp-build-data#708](https://github.com/openshift-eng/ocp-build-data/pull/708)
