### ISSUE TITLE
Operator should automatically exclude "openshift-*" namespaces

### ISSUE THREAD

**Issue by damemi** [openshift/cluster-kube-descheduler-operator#152]
No matter what config is passed, our operator should make sure to exclude `openshift-*` projects from descheduling. These are reserved namespace formats, so there should be no reason to deschedule from them in our platform

/kind bug

**Comment by damemi** [comment]
/cc @ingvagabund 
/priority important-soon
this could be tricky, because I don't think the descheduler can just take a wildcard name for excluding like that (and I don't know if that's something we want to add, could be easy to make a regex that's too wide). so this might have to be a hardcoded list or maybe there is some way to get a list of system namespaces from the client so we don't have to maintain a list in code

**Comment by ingvagabund** [comment]
If one excludes any namespace from consideration, running LowNodeUtilization might give suboptiomal performance.

Do you mean to exclude namespaces from consideration completely or exclude namespaces from eviction yet allowing strategies to process them?

**Comment by ingvagabund** [comment]
We might allow to exclude namespaces (from eviction) based on a label selector rather than based on a namespace prefix. Can't tell if all `openshift-*` namespaces have a dedicated label(s) which can be targeted.

**Comment by damemi** [comment]
> Do you mean to exclude namespaces from consideration completely or exclude namespaces from eviction yet allowing strategies to process them?

We should at least prevent openshift pods from being evicted. If that means also excluding them from processing to more accurately reflect the calculations then we should do that too, but that's what we need to figure out

> We might allow to exclude namespaces (from eviction) based on a label selector rather than based on a namespace prefix. 

This would more likely be an actual list, not just a prefix (I brought it up now since we have that capability). This should be hard-enforced by the operator, so in terms of implementation excluding by a list or excluding by managing labels on namespaces seem like the same thing (you'll still need to maintain a list of openshift namespaces to apply these labels on, at which point you could just pass the list to the namespace-exclusion config).

**Comment by ingvagabund** [comment]
I was considering how difficult it would be to provide a universal solution. In case an admin decides to extend the list of automatically excluded namespaces beyond the hard-coded list. I.e. dynamically adding/removing namespaces. If we can assume the list of `openshift-` prefixed namespaces is constant per a release, we will just need to update the hard-coded list per release. On the other hand, I'd prefer to move the responsibility for deciding which namespace has to be excluded from descheduling to owners of namespaces. If we hard-code, we need to make sure the list of namespaces is properly updated in each release. Excluding namespaces based on label(s) will have a benefit of native support in the descheduler. No need for special hard-coded list. The descheduler will just ignore eviction of any pod living in labeled namespaces, yet still taking the pods into consideration when exercising low node utilization strategy. Again, each strategy can decide if it will exclude namespace(s) completely or just from eviction.

**Comment by soltysh** [comment]
@mdame @ingvagabund and I spoke on slack about it and considering two possible approaches:
1. label namespaces to exclude from descheduling
2. hardcode a list of `openshift-*` namespaces in the operator.
We've decided to currently go with 2, since this provides us immediately with a solution. We've considered that this approach should be implemented immediately for 4.7 and tried to backport to 4.6 too. 

Number 1 is a long term goal, which will move the responsibility of updating the list of namespaces off of our team back and move it to namespace owner. Moreover, this approach will expose this mechanism to our users.

**Comment by damemi** [comment]
@soltysh @ingvagabund yes, for this release we should just hardcode the list. This is an internal system requirement for the operator so exposing any control over it to users is not a goal for this issue.

If we want to look at changing or expanding namespace controls in the upstream descheduler we can do that in another release but it shouldn't block this.

**Comment by damemi** [comment]
I think this could also be done in a better way than us having to maintain a hardcoded list, for example we could write a helper that lists all the namespaces in the cluster then constructs the excluded list by parsing that for namespaces that match that regex. I don't think it's reasonable for us to be responsible for knowing all openshift namespaces ourselves

**Comment by soltysh** [comment]
Yeah, that's fair. We basically want to exclude everything `openshift-*`
