### ISSUE TITLE
service monitors are scrapped by user workload monitoring.

### ISSUE THREAD

**Issue by germanparente** [openshift/cluster-kube-descheduler-operator#267]
I have a customer that have installed this operator in openshift 4.10

Now the alert PrometheusOperatorRejectedResources is firing. 

After checking the prometheus operator in user workload monitoring, it shows that the service monitor:

openshift-kube-descheduler-operator/kube-descheduler

is trying to be scrapped by user workload monitoring instead of by openshift-monitoring.

The label:

openshift.io/cluster-monitoring: "true"

is not found in the namespace that seems it's managed by operator.

**Comment by szymonhwheels-cloud** [comment]
> I have a customer that have installed this operator in openshift 4.10
> 
> Now the alert PrometheusOperatorRejectedResources is firing.
> 
> After checking the prometheus operator in user workload monitoring, it shows that the service monitor:
> 
> openshift-kube-descheduler-operator/kube-descheduler
> 
> is trying to be scrapped by user workload monitoring instead of by openshift-monitoring.
> 
> The label:
> 
> openshift.io/cluster-monitoring: "true"
> 
> is not found in the namespace that seems it's managed by operator.
