### ISSUE TITLE
Running tests locally won't check rbac issues

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [openshift/cluster-kube-descheduler-operator#30]
An unwanted side-effect of running tests locally in CI is rbac and deployment are not checked. This is causing issues.

/cc @sjenning

**Comment by szymonhwheels-cloud** [comment]
> An unwanted side-effect of running tests locally in CI is rbac and deployment are not checked. This is causing issues.
> 
> /cc [@sjenning](https://github.com/sjenning)
