### ISSUE TITLE
descheduler pod OOM on large clusters

### ISSUE THREAD

**Issue by huehnervater** [openshift/cluster-kube-descheduler-operator#300]
I experience on our largest openshift cluster that the descheduler pod runs out of memory. Is there a way to set the pod resources in the deployment.apps/descheduler ?

I tried to set the operator to "unmanaged" and change the deployment.apps/descheduler manually. But the operator keeps setting the default. So I had to remove the operator.

Thanks

**Comment by szymonhwheels-cloud** [comment]
> I experience on our largest openshift cluster that the descheduler pod runs out of memory. Is there a way to set the pod resources in the deployment.apps/descheduler ?
> 
> I tried to set the operator to "unmanaged" and change the deployment.apps/descheduler manually. But the operator keeps setting the default. So I had to remove the operator.
> 
> Thanks
