### ISSUE TITLE
Incorrect path to manifests in Dockerfile.metadata

### ISSUE THREAD

**Issue by dmrost** [openshift/cluster-kube-descheduler-operator#347]
For 4.13 and next versions

**Comment by ingvagabund** [comment]
`Dockerfile.metadata` is used only for testing/dev purposes. It's ok to edit it by hand if the paths no longer match.

**Comment by ingvagabund** [comment]
Addressed in https://github.com/openshift/cluster-kube-descheduler-operator/pull/357

**Comment by szymonhwheels-cloud** [comment]
> For 4.13 and next versions
