### ISSUE TITLE
system-cluster-critical pod forbidden to run

### ISSUE THREAD

**Issue by raffaelespazzoli** [openshift/cluster-kube-descheduler-operator#46]
I just deployed the descheduler operator from operator hub and got this event from the job:
```
Error creating: pods "example-descheduler-1-1571692440-" is forbidden: pods with system-cluster-critical priorityClass is not permitted in descheduler namespace
```
`descheduler` is normal project I created to run the operator. there was no special instruction on where the operator should be run. What am I doing wrong.
Also as result of this issue I now have several pending jobs, this should probably not be happening.

**Comment by szymonhwheels-cloud** [comment]
> I just deployed the descheduler operator from operator hub and got this event from the job:
> 
> ```
> Error creating: pods "example-descheduler-1-1571692440-" is forbidden: pods with system-cluster-critical priorityClass is not permitted in descheduler namespace
> ```
> 
> `descheduler` is normal project I created to run the operator. there was no special instruction on where the operator should be run. What am I doing wrong. Also as result of this issue I now have several pending jobs, this should probably not be happening.



> I just deployed the descheduler operator from operator hub and got this event from the job:
> 
> ```
> Error creating: pods "example-descheduler-1-1571692440-" is forbidden: pods with system-cluster-critical priorityClass is not permitted in descheduler namespace
> ```
> 
> `descheduler` is normal project I created to run the operator. there was no special instruction on where the operator should be run. What am I doing wrong. Also as result of this issue I now have several pending jobs, this should probably not be happening.
