### ISSUE TITLE
README inconsistencies

### ISSUE THREAD

**Issue by bergerhoffer** [openshift/cluster-kube-descheduler-operator#74]
In testing the operator, found two minor inconsistencies from the README file.

1. The README references the `openshift-descheduler-operator` namespace twice, but it's actually the `openshift-kube-descheduler-operator` namespace.
2. The Sample CR section says that the operator expects the name `config`, but the name is `cluster` when created.

**Comment by bergerhoffer** [comment]
@damemi Just FYI this is still an issue.

**Comment by damemi** [comment]
@bergerhoffer thanks for the reminder, I opened https://github.com/openshift/cluster-kube-descheduler-operator/pull/142 to fix these but I think I'll need to open a BZ as well.

Can you check that PR to make sure I got everything?
