### ISSUE TITLE
Update readme with new manual deployment options

### ISSUE THREAD

**Issue by damemi** [openshift/cluster-kube-descheduler-operator#84]
Just opening this to track these updates. With the switch to operatorhub setup, I'd still like to know how I can manually deploy the operator from source if possible (does `oc create -f manifests/.` still work?)

**Comment by damemi** [comment]
There are new steps provided by @ingvagabund here: https://github.com/openshift/cluster-kube-descheduler-operator/pull/79#issuecomment-588975449

**Comment by damemi** [comment]
I think this is covered in https://github.com/openshift/cluster-kube-descheduler-operator/pull/94
/close

**Comment by szymonhwheels-cloud** [comment]
> Just opening this to track these updates. With the switch to operatorhub setup, I'd still like to know how I can manually deploy the operator from source if possible (does `oc create -f manifests/.` still work?)



> Just opening this to track these updates. With the switch to operatorhub setup, I'd still like to know how I can manually deploy the operator from source if possible (does `oc create -f manifests/.` still work?)
